### ISSUE TITLE
Issue when reusing a previous i2 Schema

### ISSUE THREAD

**Issue by mdiass** [IBM-i2/analyze-connect#9]
Hello,

I have an existing i2 Schema that I use in custom connector using i2 Connector Creator with i2 Analyze 4.1.2.
Now I am trying to write a new connector using i2 Connect Gateway with i2 Analyze 4.3.3 with this same i2 Schema.

I was able to open this previous i2 Schema in Schema Designer 4.3.3 and I wrote a very simple connector example (just one acquire url with a test data).

But, when I start i2 Analyze I got the following error message:

 # [opal-services-daod] Failed to retrieve configuration information from the connector with identifier 'fci-i2-connector': com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.i2group.apollo.model.schema.transport.ProhibitedOperation, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information at [Source: java.io.StringReader@6ba09452; line: 1, column: 20610] (through reference chain: com.i2group.apollo.model.schema.transport.Schema["itemTypes"]->com.i2group.apollo.model.schema.transport.ItemTypes["entityTypes"]->java.util.ArrayList[5]->com.i2group.apollo.model.schema.transport.EntityType["propertyTypes"]->java.util.ArrayList[7]->com.i2group.apollo.model.schema.transport.PropertyType["prohibitedOperations"]->java.util.ArrayList[0])

Is there anything I should change/fix on my schema before using it on my custom connector?

Thanks in advance

**Comment by colvinco** [comment]
Hello,

>->java.util.ArrayList[7]->com.i2group.apollo.model.schema.transport.PropertyType["prohibitedOperations"]->java.util.ArrayList[0])

These `prohibitedOperations` that the error is referencing in your schema are unsupported in the Information Store / i2 Connect products. In the latest release (4.3.4) the error you've encountered has been fixed and the `prohibitedOperations` will be ignored. In 4.3.3 you can use Schema Designer to either _enable_ (:heavy_check_mark:) or _delete_ (:x:) any types that are marked as `Hidden` or `Disabled`. Enabling a type will remove the `prohibitedOperations` elements from that type, and deleting it will remove the type entirely. See below:

![image](https://user-images.githubusercontent.com/51863265/128832909-4cc7392d-ad94-4747-9371-1d831a5c1bc6.png)

Note: in 4.3.4 any `prohibitedOperations` are simply ignored, so a type marked as `Hidden` or `Disabled` would be no treated the same way as an `Enabled` type.

**Comment by mdiass** [comment]
@colvinco Thanks for the explanation!
Actually, these prohibitedOperations are not mandatory for my new deployment.
I removed it from my schema file and now the basic connector is working properly.
